<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "url": "https://galliummarket.com/Home.html#sec-f068",
    "brand": {
      "@type": "Brand",
      "logo": "https://galliummarket.com/images/gem-modified.png?rand=a880"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "description": "We offer a wide range of top-quality clients at affordable prices designed to give you the greatest advantage.",
    "url": "https://discord.gg/Ww2JgdAUer",
    "brand": {
      "@type": "Brand",
      "name": "Gallium Market"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "bestRating": "Best Clients and Cheat Services"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "Revenant",
    "image": "https://galliummarket.com/images/RevLogo.png",
    "description": "The Revenant mod menu, formerly recognized as Spooky, has gained a formidable reputation among the GTA modding community. It is widely considered as one of the best low-cost menus for GTA, providing a range of user interfaces, unique features, and enjoyable options that are certain to cater to your needs.",
    "url": "https://discord.gg/Ww2JgdAUer",
    "brand": {
      "@type": "Brand",
      "name": "Gallium Market"
    },
    "offers": {
      "@type": "Offer",
      "price": "$8.00"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "bestRating": "Best Clients and Cheat Services"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "description": "Gallium Market offers the best clients and services for your games. We did not create any of the software, and are not responsible for any account bans.",
    "url": "https://panel.revenantcheats.com/Identity/Account/Register"
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "url": "https://discord.gg/Ww2JgdAUer"
  }
]
</script>
